### ISSUE TITLE
Question about order of operation in generating pseudo bulk data for differential expression

### ISSUE THREAD

**Issue by holgerman** [OSCA-source/OSCA.multisample#11]
Dear authors,

thanks so much for OSCA, an incredibly helpful resource! 

I have a question about pseudo bulk differential expression.
In https://bioconductor.org/books/3.14/OSCA.multisample/multi-sample-comparisons.html#creating-pseudo-bulk-samples, filtering genes by filterByExpr() is done before calcNormFactors(). 
Why is the order not opposite, i.e. first norm factor calculation, than excluding low expressed genes,  or asked differently, why should counts of low expressed genes not contribute to the library size?
Thank you very much,
Holger

**Comment by lgeistlinger** [comment]
Hi Holger:

> why should counts of low expressed genes not contribute to the library size?

Note that the library sizes are computed at the time of the `DGEList` construction. In the section of the OSCA book that you are referring to, the counts of low expressed genes thus do contribute to the library size.

Further, from the edgeR vignette, Section 2.7:

"It is recommended to recalculate the library sizes of the `DGEList` object after the filtering, although the downstream analysis is robust to whether this is done or not."

That means you would want first remove noise (= low expressed genes) and then do the normalization on the updated library sizes to reflect that certain genes/counts have been removed, although it seems to not make a big difference in practice whether you perform normalization on the actual or updated library sizes.

**Comment by holgerman** [comment]
This is very helpful, thank you!
