### ISSUE TITLE
Failure to compile pijuan-embryo.Rmd in BioC 3.18

### ISSUE THREAD

**Issue by PeteHaitch** [OSCA-source/OSCA.multisample#12]
I've been trying to debug the current build failure of **OSCA.multisample** in BioC 3.18 (https://bioconductor.org/checkResults/3.18/books-LATEST/OSCA.multisample/nebbiolo2-buildsrc.html).
Working locally on my Ubuntu laptop, the error I get when trying to compile the `pijuan-embryo.Rmd` chapter is as follows:

```r
> rmarkdown::render("inst/book/pijuan-embryo.Rmd")


processing file: pijuan-embryo.Rmd
  |......................                                |  40% [normalization]           
Quitting from lines 47-48 [normalization] (pijuan-embryo.Rmd)
Error in `lazyLoadDBinsertVariable()`:
! long vectors not supported yet: connections.c:6093
Backtrace:
  1. rmarkdown::render("inst/book/pijuan-embryo.Rmd")
  2. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  3. knitr:::process_file(text, output)
  8. knitr:::process_group.block(group)
  9. knitr:::call_block(x)
     ...
 11. knitr:::eng_r(options)
 12. knitr:::block_cache(options, output, objs)
 13. cache$save(objects, outname, hash, lazy = options$cache.lazy)
 14. getFromNamespace("makeLazyLoadDB", "tools")(...)
 15. tools (local) lazyLoadDBinsertVariable(...)
```

Seems to be something with the **knitr** cache but I don't know much more than that.
@ltla: Do you remember seeing this before or have ideas to fix/workaround it?

**Comment by LTLA** [comment]
I've seen this before, and it happens when **knitr** tries to cache objects that are too large. I'm curious why it suddenly started erroring, though. I thought that I had set `cache=FALSE` in all of the problematic chunks.

**Comment by PeteHaitch** [comment]
Yeah it's weird that it's just cropped up now.
I haven't spotted any changes in **knitr**'s caching stuff or in packages used in this chapter that might have caused the `sce.chimera` object to be larger than it used to be.
I did see that the assays of `sce.chimera` are _dgTMatrix_ objects, which makes each ~30% larger than they'd otherwise be if they were _dgCMatrix_ ... I've no idea why they are stored that way, but that doesn't seem like a recent change to this dataset.

Anyway, chucking in a strategic `cache.lazy=FALSE` seems to work around the issue.
I'll make and merge a PR and then push to BioC.

**Comment by LTLA** [comment]
IIRC the caching was primarily intended to enable re-use of artifacts between chapters and even books. As clever as it was, though, it introduced a web of interdependencies between Rmarkdown files that probably makes life more difficult than it needed to be. The next version of the book might consider breaking these dependency relationships by just, e.g., copying the minimal code from the source chapter and just re-running it to create an example object to start the new chapter.

Maybe with the new to-be-named-later package based on the **libscran** C++ code, things will be fast enough that we won't need to worry about trying to save runtime by re-using precomputed results.
