### ISSUE TITLE
Differential abundance analysis

### ISSUE THREAD

**Issue by IrSoler** [OSCA-source/OSCA.multisample#5]
Dear OSCA team,

In the book you explain why we need to normalize only based on the “library size” in differential abundance analysis (DA) but in the code attached (chapter 6.2. Performing DA analysis) I cannot see any normalization applied to the data (e.g. cpm function). 

I was wondering if I have misunderstood the usage of this pipeline or if this is an issue to report.

By the way, thank you so much for elaborating this amazing resource! 

Best wishes,

Irene

**Comment by LTLA** [comment]
**edgeR** will automatically use library size normalization if nothing else is done (e.g., if you don't call `calcNormFactors()` or set `y$samples$norm.factors` manually.

**Comment by IrSoler** [comment]
I didn't know that. Thank you so much!
